#!/usr/bin/env python

import sys

from remora_console.my_module import MyPlugin
from rqt_gui.main import Main

plugin = 'basic_console'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
